### ISSUE TITLE
_is_balanced function returns wrong value

### ISSUE THREAD

**Issue by kgashok** [joowani/binarytree#22]
The function `_is_balanced` always returns `1 + height`. What gives? 

```python
import binarytree
ttree = binarytree.tree(height=3, is_perfect=True)
print(ttree)
assert ttree.height == binarytree._is_balanced(ttree), \
f'Tree property height: {ttree.height} is not equal to \
_is_balanced function return value: {binarytree._is_balanced(ttree)}' 
```
You can also visit https://repl.it/@ashokb/binarytreeBalanced to run it

**Comment by joowani** [comment]
Hi @kgashok,

Are you asking why the function returns `1 + height` instead of `True/False`, or are you asking why it returns `1+ height` instead of just `height`?

If it is the former: this is just a clever way to catch two birds with one stone and minimize code. -1 means `False` whereas all other non-negative integer means `True`. Using this convention, we can pass two information up the recursive tree at the same time: 1) the height of the current subtree, and 2) whether the current subtree is balanced.

If it is the latter: I guess I need update the docstring to say `height + 1` instead of just `height` for correctness (will do in the next release). But this is a private function not meant to be exposed as public API so you shouldn't be using it anyway. 

Let me know if you have any more questions. Thanks.
