### ISSUE TITLE
add `_repr_svg_` for svg display in notebooks

### ISSUE THREAD

**Issue by benabel** [joowani/binarytree#29]
Hi, and first thanks for this handy package. I'm using it with my students, and even if I really like the print method, I would like to have better outputs as I am using it on notebooks.

I've implemented a regular tree display in svg format. It allows outputs like this:

![image](https://user-images.githubusercontent.com/12530561/104582168-d9269b80-565f-11eb-878c-49e0bc56a19d.png)

Are you interested in this feature, it do not change anything except in notebooks, where the traditionnal print method will still work.

For reference here is the doc for `_repr_svg_`:

https://ipython.readthedocs.io/en/stable/config/integrating.html?highlight=repr_svg#rich-display

**Comment by joowani** [comment]
Hi @benabel,

While I'm hesitant to add more complexities & dependencies to the library (its simplicity and lightweight-ness is what I like most about it), it does seem like a cool addition. Please feel free to make a PR!

**Comment by benabel** [comment]
Ok, @joowani I'll open the PR soonly when I get some time.

**Comment by joowani** [comment]
Hi @benabel,

Instead of implementing this method from scratch, I've decided to use [python-graphviz](https://pypi.org/project/graphviz) instead (it has many more features including Jupyter notebook support) in version 6.0.0. Please see the [documentation](https://binarytree.readthedocs.io/en/main/graphviz.html) for more details! Thanks.
