### ISSUE TITLE
Question about node index

### ISSUE THREAD

**Issue by Roland-djee** [joowani/binarytree#35]
Hello,

A quick question if that is the place to ask, is it possible to access the index of an individual node ?

I can't seem to find an easy way to do that.

Thanks !

**Comment by joowani** [comment]
Hi @Roland-djee,

The short answer is no. Index calculation is always done on-the-fly from the root node (the node you are indexing from). Nodes cannot have "absolute" indexes since the they are relative to the root node you pick. But I suppose we can add a method like `binarytree.Node.get_index_from_root(other)`  that would either return -1 or raise an error if `other` is not an ancestor, else calculate and return the index.

**Comment by joowani** [comment]
I added [get_index](https://binarytree.readthedocs.io/en/main/specs.html#function-binarytree-get-index) function in release [6.4.0](https://github.com/joowani/binarytree/releases/tag/6.4.0) that should almost cover your use case.

**Comment by Roland-djee** [comment]
Thanks !
