### ISSUE TITLE
Add comments on algorithms to "_build_str" function.

### ISSUE THREAD

**Issue by lgsunnyvale** [joowani/binarytree#4]
Hi, I find this project superb cool. I read through the code in the first time. All code are concise and good. But I am having a hard time trying to understand the algorithm to pretty-print(pprint) the tree. 

Can you add more comments to explain how it works? It seems the code is building up the node value and formatting ascii strings level by level. But I am very curious about the idea behind, like what does l_len, l_vale_from, l_anhor works? what l_anchor is marked as ceiling and r_anchor as floor?

```
def _build_str(node):
    """Helper function used for pretty-printing."""
    if node == _null:
        return 0, 0, 0, []

    line1 = []
    line2 = []
    val_len = gap_len = len(str(_value_of(node)))

    l_len, l_val_from, l_val_to, l_lines = _build_str(_left_of(node))
    r_len, r_val_from, r_val_to, r_lines = _build_str(_right_of(node))

    if l_len > 0:
        l_anchor = -int(-(l_val_from + l_val_to) / 2) + 1  # ceiling
        line1.append(' ' * (l_anchor + 1))
        line1.append('_' * (l_len - l_anchor))
        line2.append(' ' * l_anchor + '/')
        line2.append(' ' * (l_len - l_anchor))
        val_from = l_len + 1
        gap_len += 1
    else:
        val_from = 0

    line1.append(str(_value_of(node)))
    line2.append(' ' * val_len)

    if r_len > 0:
        r_anchor = int((r_val_from + r_val_to) / 2)  # floor
        line1.append('_' * r_anchor)
        line1.append(' ' * (r_len - r_anchor + 1))
        line2.append(' ' * r_anchor + '\\')
        line2.append(' ' * (r_len - r_anchor))
        gap_len += 1
    val_to = val_from + val_len - 1

    gap = ' ' * gap_len
    lines = [''.join(line1), ''.join(line2)]
    for i in range(max(len(l_lines), len(r_lines))):
        l_line = l_lines[i] if i < len(l_lines) else ' ' * l_len
        r_line = r_lines[i] if i < len(r_lines) else ' ' * r_len
        lines.append(l_line + gap + r_line)

    return len(lines[0]), val_from, val_to, lines
```

**Comment by joowani** [comment]
Hi @lgsunnyvale!

I am glad that you find interest in **binarytree**! I didn't bother commenting as I thought no one would really look but you proved me wrong :)

This is a giant recursion where in each recursive call, I concatenate characters level by level (or line by line) and ultimately build what to print. I ensure that each line is of the same length by padding with whitespace so that I end up with a _rectangular box_ of characters. This box would be the ascii representation of the current subtree. Then I measure its dimensions (i.e. `len(lines[0])` x `lines`). I also find out the start and end positions of the _root_ value in the top line (i.e. `val_from` to `val_to`). I need `val_from` and `val_to` so I can connect the branches from the parent node in a "pretty" fashion. Once I have the numbers, I pass them up the recursion tree along with the ascii box. In the parent call, the ascii box(es) and their measurements from left and right children are combined to make a bigger box, and so on.

I hope that was clear. Once I find some time, I will improve the comments for the function in the next release (perhaps with diagrams for better understanding).

**Comment by lgsunnyvale** [comment]
Thanks @joowani! That's very helpful. Makes a lot more sense now. I will try to write some test cases to illustrate the point. 😃

**Comment by joowani** [comment]
I added more comments to the function in https://github.com/joowani/binarytree/releases/tag/1.1.1.
